# application-local.yml
server:
  port: 8080

env:
  imageServerPath: imageServerUrl

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/want_car
    username: sa